"""
Cohere Embedding Service for Backend Multi-Agent System for Book RAG Chatbot

This module provides text vectorization using Cohere embeddings for similarity matching.
"""
from typing import List, Union
import cohere
import os
from dotenv import load_dotenv
import logging

load_dotenv()

logger = logging.getLogger(__name__)

class CohereEmbeddingService:
    """
    Service class for generating text embeddings using Cohere
    """

    def __init__(self):
        """
        Initialize the Cohere client
        """
        api_key = os.getenv("COHERE_API_KEY")
        if not api_key:
            raise ValueError("COHERE_API_KEY environment variable is required")

        self.client = cohere.Client(api_key)
        self.model = "embed-multilingual-v2.0"  # Using a robust multilingual model

    def generate_embedding(self, text: str) -> List[float]:
        """
        Generate a single embedding for the provided text

        Args:
            text: The text to embed

        Returns:
            A list of floats representing the embedding vector
        """
        try:
            response = self.client.embed(
                texts=[text],
                model=self.model
            )
            embedding = response.embeddings[0]
            logger.info(f"Generated embedding for text of length {len(text)}")
            return embedding
        except Exception as e:
            logger.error(f"Failed to generate embedding: {str(e)}")
            raise

    def generate_embeddings(self, texts: List[str]) -> List[List[float]]:
        """
        Generate embeddings for multiple texts

        Args:
            texts: List of texts to embed

        Returns:
            A list of embedding vectors (each vector is a list of floats)
        """
        try:
            response = self.client.embed(
                texts=texts,
                model=self.model
            )
            embeddings = [embedding for embedding in response.embeddings]
            logger.info(f"Generated {len(embeddings)} embeddings for {len(texts)} texts")
            return embeddings
        except Exception as e:
            logger.error(f"Failed to generate embeddings: {str(e)}")
            raise

    def get_embedding_dimensions(self) -> int:
        """
        Get the dimension of the embeddings generated by this service

        Returns:
            The number of dimensions in the embedding vectors
        """
        # Test embedding to determine dimensions
        test_embedding = self.generate_embedding("test")
        return len(test_embedding)


# Global instance for easy access
cohere_embedding_service = CohereEmbeddingService()