"""
Data Models for Backend Multi-Agent System for Book RAG Chatbot

This module defines the core data structures based on data-model.md
including UserQuery, AgentResponse, RetrievedContext, and AgentState.
"""
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any
from datetime import datetime
from enum import Enum


class AgentType(Enum):
    """Enumeration of agent types in the system"""
    TRIAGE = "triage"
    QUERY = "query"


@dataclass
class UserQuery:
    """
    The input from the user that initiates the agent interaction.

    Fields:
    - query_text: The question or request from the user
    - selected_text: Specific text provided by user that overrides general retrieval
    - user_context: Additional context about the user's session or preferences
    - timestamp: When the query was submitted
    """
    query_text: str
    selected_text: Optional[str] = None
    user_context: Optional[Dict[str, Any]] = None
    timestamp: datetime = field(default_factory=datetime.now)

    def __post_init__(self):
        """Validate the UserQuery after initialization"""
        if not self.query_text or not self.query_text.strip():
            raise ValueError("query_text must not be empty")

        if self.selected_text and len(self.selected_text.strip()) < 10:
            raise ValueError("selected_text, if provided, must be meaningful length (>10 characters)")

    def has_selected_text(self) -> bool:
        """Check if the query includes selected text that should override retrieval"""
        return bool(self.selected_text and self.selected_text.strip())


@dataclass
class RetrievedContext:
    """
    The relevant passages retrieved from book content for answering the query.

    Fields:
    - passages: List of relevant text passages from the book
    - similarity_scores: Similarity scores for each passage (0.0-1.0)
    - source_metadata: Metadata about the source of each passage (chapter, page, etc.)
    - retrieval_method: How the context was retrieved ("selected_text", "vector_search")
    """
    passages: List[str]
    similarity_scores: List[float] = field(default_factory=list)
    source_metadata: List[Dict[str, Any]] = field(default_factory=list)
    retrieval_method: str = "vector_search"  # Default to vector search

    def __post_init__(self):
        """Validate the RetrievedContext after initialization"""
        if self.retrieval_method == "vector_search" and not self.passages:
            raise ValueError("passages array must not be empty when retrieval_method is 'vector_search'")

        if len(self.similarity_scores) != len(self.passages):
            raise ValueError("similarity_scores must correspond to the passages array")

        for score in self.similarity_scores:
            if not 0.0 <= score <= 1.0:
                raise ValueError("similarity_scores must be between 0.0 and 1.0")


@dataclass
class AgentResponse:
    """
    The output from the agent system to the user.

    Fields:
    - answer: The final answer generated by the system
    - source_references: List of references to the book content used in the answer
    - confidence_score: Confidence level in the answer (0.0-1.0)
    - processing_time: Time taken to process the query in seconds
    - was_handoff: Whether the query was handed off from triage to query agent
    """
    answer: str
    source_references: List[Dict[str, Any]] = field(default_factory=list)
    confidence_score: float = 1.0
    processing_time: float = 0.0
    was_handoff: bool = False

    def __post_init__(self):
        """Validate the AgentResponse after initialization"""
        if not self.source_references:
            raise ValueError("source_references must not be empty when answer is provided")

        if not 0.0 <= self.confidence_score <= 1.0:
            raise ValueError("confidence_score must be between 0.0 and 1.0")


@dataclass
class AgentState:
    """
    The internal state maintained by the agent system during processing.

    Fields:
    - current_agent: The agent currently processing the request ("triage", "query")
    - query_classification: The classification result from triage ("book-related", "other")
    - context_used: The context used for answering
    - processing_steps: List of steps taken during processing
    """
    current_agent: AgentType
    query_classification: str = "unknown"
    context_used: Optional[RetrievedContext] = None
    processing_steps: List[str] = field(default_factory=list)

    def __post_init__(self):
        """Validate the AgentState after initialization"""
        if not isinstance(self.current_agent, AgentType):
            raise ValueError("current_agent must be a valid AgentType")

        valid_classifications = ["book-related", "other", "unknown"]
        if self.query_classification not in valid_classifications:
            raise ValueError(f"query_classification must be one of {valid_classifications}")


# Additional helper functions for working with models

def create_user_query(query_text: str, selected_text: Optional[str] = None,
                     user_context: Optional[Dict[str, Any]] = None) -> UserQuery:
    """Helper function to create a validated UserQuery instance"""
    return UserQuery(
        query_text=query_text,
        selected_text=selected_text,
        user_context=user_context
    )


def create_agent_response(answer: str, source_references: List[Dict[str, Any]],
                         confidence_score: float = 1.0, processing_time: float = 0.0,
                         was_handoff: bool = False) -> AgentResponse:
    """Helper function to create a validated AgentResponse instance"""
    return AgentResponse(
        answer=answer,
        source_references=source_references,
        confidence_score=confidence_score,
        processing_time=processing_time,
        was_handoff=was_handoff
    )