"""
Qdrant Client Wrapper for Backend Multi-Agent System for Book RAG Chatbot

This module provides a wrapper around the Qdrant client for vector operations
including storing, searching, and managing book content embeddings.
"""
from typing import List, Dict, Optional, Any
import logging
from qdrant_client import QdrantClient
from qdrant_client.http import models
from qdrant_client.http.models import Distance, VectorParams
import uuid
import os
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

class QdrantClientWrapper:
    """
    Wrapper class for Qdrant client operations
    """

    def __init__(self, collection_name: str = "book_content"):
        """
        Initialize the Qdrant client wrapper

        Args:
            collection_name: Name of the Qdrant collection to use
        """
        self.collection_name = collection_name
        self.client = QdrantClient(
            url=os.getenv("QDRANT_URL"),
            api_key=os.getenv("QDRANT_API_KEY"),
        )
        self._ensure_collection_exists()

    def _ensure_collection_exists(self):
        """
        Ensure the collection exists with appropriate vector configuration
        """
        try:
            # Check if collection exists
            collection_info = self.client.get_collection(self.collection_name)
            logger.info(f"Collection {self.collection_name} already exists with config: {collection_info.config}")
        except Exception:
            # Create collection if it doesn't exist
            # Using Cohere's multilingual embedding model which produces 1024-dim vectors
            self.client.recreate_collection(
                collection_name=self.collection_name,
                vectors_config=VectorParams(size=1024, distance=Distance.COSINE),
            )
            logger.info(f"Created new collection {self.collection_name} with 1024-dim vectors")

    def setup_book_content_collection(self, recreate: bool = False):
        """
        Explicitly set up the book content collection with appropriate configuration

        Args:
            recreate: Whether to recreate the collection (deleting existing data)
        """
        if recreate:
            self.client.recreate_collection(
                collection_name=self.collection_name,
                vectors_config=VectorParams(size=1024, distance=Distance.COSINE),
            )
            logger.info(f"Recreated collection {self.collection_name}")
        else:
            # Just ensure it exists with proper configuration
            self._ensure_collection_exists()

    def store_embedding(self, text: str, metadata: Dict[str, Any], text_id: Optional[str] = None) -> str:
        """
        Store a text embedding in Qdrant

        Args:
            text: The text to embed and store
            metadata: Additional metadata to store with the text
            text_id: Optional ID for the text (generated if not provided)

        Returns:
            The ID of the stored text
        """
        if text_id is None:
            text_id = str(uuid.uuid4())

        # In a real implementation, we would call Cohere to generate the embedding
        # For now, we'll just store the text with metadata
        # The actual embedding would be generated by the embedding service

        points = [
            models.PointStruct(
                id=text_id,
                vector=[0.0] * 1024,  # Placeholder - would be actual embedding
                payload={
                    "text": text,
                    "metadata": metadata
                }
            )
        ]

        self.client.upsert(
            collection_name=self.collection_name,
            points=points
        )

        logger.info(f"Stored embedding for text ID: {text_id}")
        return text_id

    def store_embedding_with_vector(self, embedding: List[float], text: str, metadata: Dict[str, Any], text_id: str = None):
        """
        Store a text with a pre-computed embedding vector in Qdrant

        Args:
            embedding: The pre-computed embedding vector
            text: The text to store
            metadata: Additional metadata to store with the text
            text_id: Optional ID for the text (generated if not provided)

        Returns:
            The ID of the stored text
        """
        if text_id is None:
            text_id = str(uuid.uuid4())

        points = [
            models.PointStruct(
                id=text_id,
                vector=embedding,
                payload={
                    "text": text,
                    "metadata": metadata
                }
            )
        ]

        self.client.upsert(
            collection_name=self.collection_name,
            points=points
        )

        logger.info(f"Stored embedding with vector for text ID: {text_id}")
        return text_id

    def search_similar(self, query_vector: List[float], limit: int = 5) -> List[Dict[str, Any]]:
        """
        Search for similar text embeddings

        Args:
            query_vector: The vector to search for similarity
            limit: Maximum number of results to return

        Returns:
            List of similar text passages with metadata and similarity scores
        """
        results = self.client.search(
            collection_name=self.collection_name,
            query_vector=query_vector,
            limit=limit
        )

        # Format results
        formatted_results = []
        for result in results:
            formatted_results.append({
                "id": result.id,
                "text": result.payload.get("text", ""),
                "metadata": result.payload.get("metadata", {}),
                "similarity_score": result.score
            })

        logger.info(f"Found {len(formatted_results)} similar passages")
        return formatted_results

    def batch_store_embeddings(self, texts: List[Dict[str, Any]]) -> List[str]:
        """
        Store multiple text embeddings at once

        Args:
            texts: List of dictionaries with 'text' and 'metadata' keys

        Returns:
            List of IDs for the stored texts
        """
        ids = []
        points = []

        for item in texts:
            text_id = str(uuid.uuid4())
            ids.append(text_id)

            points.append(models.PointStruct(
                id=text_id,
                vector=[0.0] * 1024,  # Placeholder - would be actual embedding
                payload={
                    "text": item["text"],
                    "metadata": item["metadata"]
                }
            ))

        self.client.upsert(
            collection_name=self.collection_name,
            points=points
        )

        logger.info(f"Batch stored {len(texts)} embeddings")
        return ids


# Global instance for easy access (can be configured differently if needed)
qdrant_client_wrapper = QdrantClientWrapper()